services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: capital-gains
    stdin_open: true
    tty: false

  test:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -lc "npm ci && npm test"

